-- AlterTable
ALTER TABLE "ProductSize" ALTER COLUMN "height" DROP DEFAULT,
ALTER COLUMN "insurance_value" DROP DEFAULT,
ALTER COLUMN "length" DROP DEFAULT,
ALTER COLUMN "quantity" DROP DEFAULT,
ALTER COLUMN "weight" DROP DEFAULT,
ALTER COLUMN "width" DROP DEFAULT;
